server:
  port: 8090

spring:
  profiles:
    active: dev  # Set the default active profile
  datasource:
    url: jdbc:mysql://localhost/rockburgerapp
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

            requestInterceptors:
              - com.rockburger.arquetipo2024.adapters.driven.feign.config.JwtTokenInterceptor


jwt:
  secret: "9qZgHlZ5Kg+POpcNp1YWlN5F/mkDoYysAaMAzvCydswRhE+tzLXytB/bNiU+NjPiCbKN7UZWFkgtw0wXSDYWQg=="  #WhileTesting
  expiration: 3600000 #60minsWhileTesting

logging:
  level:
    org.springframework.security: DEBUG
    com.rockburger.arquetipo2024: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j: DEBUG

---
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      getActiveCart:
        baseConfig: default
      addItemToCart:
        baseConfig: default
      removeItemFromCart:
        baseConfig: default
      clearCart:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      getActiveCart:
        baseConfig: default
      addItemToCart:
        baseConfig: default
      removeItemFromCart:
        baseConfig: default
      clearCart:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      getActiveCart:
        baseConfig: default
      addItemToCart:
        baseConfig: default
      removeItemFromCart:
        baseConfig: default
      clearCart:
        baseConfig: default

---
spring:
  config:
    activate:
      on-profile: dev
cart:
  service:
    url: http://localhost:8091

---
spring:
  config:
    activate:
      on-profile: prod
cart:
  service:
    url: https://cart-service.rockburger.com